language: c
dist: xenial

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then which -a brew && brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install tcl-tk; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --force --overwrite tcl-tk; fi

script:
  - cd tnm
  - autoreconf -vi
  - if [ -f /usr/local/lib/tclConfig.sh ]; then ./configure --with-tcl=/usr/local/lib; else ./configure; fi
  - make
  - if [[ $(uname -s) == "Linux" ]]; then sudo make install; fi
  - if [[ $(uname -s) == "Linux" ]]; then sudo make sinstall; fi
