language: c
dist: xenial

os:
  - linux
  - osx

before_install:
  - export HOMEBREW_NO_EMOJI=1 HOMEBREW_BOOTSNAP=1 HOMEBREW_CURL_VERBOSE=1 HOMEBREW_VERBOSE=1 HOMEBREW_VERBOSE_USING_DOTS=1
  - export GIT_CURL_VERBOSE=1 && env | sort | uniq
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then which -a brew && brew update -v --auto-update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ca-certificates && brew install tcl-tk; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --force --overwrite tcl-tk; fi

script:
  - cd tnm
  - autoreconf -vi
  - if [ -f /usr/local/lib/tclConfig.sh ]; then ./configure --with-tcl=/usr/local/lib; else ./configure; fi
  - make
  - if [[ $(uname -s) == "Linux" ]]; then sudo make install; fi
  - if [[ $(uname -s) == "Linux" ]]; then sudo make sinstall; fi
