name: cooljeanius/scotty
on:
  push:
    branches:
    - "**/*"
  pull_request:
concurrency:
#   # This item has no matching transformer
#   maximum_number_of_builds: 0
jobs:
  test:
    runs-on: ${{ matrix.os }}
    steps:
    - name: checkout
      uses: actions/checkout@v4.0.0
    - run: if [[ "${{ runner.os }}" == "osx" ]]; then which -a brew && brew update; fi
    - run: if [[ "${{ runner.os }}" == "osx" ]]; then brew install tcl-tk; fi
    - run: if [[ "${{ runner.os }}" == "osx" ]]; then brew link --force --overwrite tcl-tk; fi
    - run: cd tnm
    - run: autoreconf -vi
    - run: if [ -f /usr/local/lib/tclConfig.sh ]; then ./configure --with-tcl=/usr/local/lib; else ./configure; fi
    - run: make
    - run: if [[ $(uname -s) == "Linux" ]]; then sudo make install; fi
    - run: if [[ $(uname -s) == "Linux" ]]; then sudo make sinstall; fi
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
