name: cooljeanius/scotty
on:
  push:
    branches:
    - "**/*"
  pull_request:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: if [[ "${{ runner.os }}" == "osx" ]]; then brew update; elif [[ "${{ runner.os }}" == "Linux" ]]; then sudo apt-get update; fi
    - run: if [[ "${{ runner.os }}" == "osx" ]]; then brew install tcl-tk; elif [[ "${{ runner.os }}" == "Linux" ]]; then sudo apt-get install tcl pkg-config findutils libtirpc-dev mingw-w64 mlocate wine wine64; fi
    - run: if [[ "${{ runner.os }}" == "osx" ]]; then brew link --force --overwrite tcl-tk; elif [[ "${{ runner.os }}" == "Linux" ]]; then locate arpa/nameser.h; fi
    - run: cd tnm && autoreconf -vi
    - run: if [[ "${{ runner.os }}" == "Linux" ]]; then if test -x "$(which updatedb)" -a -w /var/lib/plocate; then updatedb; elif test -x "$(which gupdatedb)" -a -w /var/locatedb; then gupdatedb; fi; (locate tclConfig.sh || sudo find / -name tclConfig.sh);  fi
    - run: cd tnm && if [ -f /usr/local/lib/tclConfig.sh ]; then ./configure --with-tcl=/usr/local/lib; elif [ -f /usr/share/miniconda/lib/tclConfig.sh ]; then ./configure --with-tcl=/usr/share/miniconda/lib; else ./configure; fi
    - run: cd tnm && if [[ "${{ runner.os }}" == "Linux" ]]; then stat compat && make -ki CFLAGS="-Wno-error=implicit-function-declaration -Wno-attributes -Icompat -D__TNM_CONFIG_H__ -DINET_ADDRSTRLEN=16"; else make CFLAGS="-Wno-error=implicit-function-declaration -Wno-attributes"; fi
    - run: cd tnm && if [[ $(uname -s) == "Linux" ]]; then sudo make -ki install; fi
    - run: cd tnm && if [[ $(uname -s) == "Linux" ]]; then sudo make sinstall; fi
    - run: ls -AR; sleep 1; if test -x "$(which clear)" -a -n "${TERM}" -a "${TERM}" != "dumb"; then echo "clear is $(which clear) and TERM is ${TERM}"; clear; else echo "(end of file listing output)"; fi; echo "whoami? $(whoami)"; sleep 1
      if: "${{ failure() }}"
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
