name: cooljeanius/scotty
on:
  push:
    branches:
    - "**/*"
  pull_request:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: if [[ "${{ runner.os }}" == "osx" ]]; then brew update; elif [[ "${{ runner.os }}" == "Linux" ]]; then sudo apt-get update; fi
    - run: if [[ "${{ runner.os }}" == "osx" ]]; then brew install tcl-tk; elif [[ "${{ runner.os }}" == "Linux" ]]; then sudo apt-get install tcl pkg-config findutils libtirpc-dev mlocate; fi
    - run: if [[ "${{ runner.os }}" == "osx" ]]; then brew link --force --overwrite tcl-tk; fi
    - run: cd tnm && autoreconf -vi
    - run: cd tnm && if [ -f /usr/local/lib/tclConfig.sh ]; then ./configure --with-tcl=/usr/local/lib; else locate tclConfig.sh && ./configure; fi
    - run: cd tnm && make CFLAGS="-Wno-error=implicit-function-declaration"
    - run: cd tnm && if [[ $(uname -s) == "Linux" ]]; then sudo make install; fi
    - run: cd tnm && if [[ $(uname -s) == "Linux" ]]; then sudo make sinstall; fi
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
